name: Deploy Quartz

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your notes
        uses: actions/checkout@v3
        with:
          path: content

      - name: Checkout Quartz
        uses: actions/checkout@v3
        with:
          repository: jackyzha0/quartz
          path: quartz

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Move your content into Quartz
        run: |
          rm -rf quartz/content
          mv content quartz/content

      - name: Install dependencies
        run: |
          cd quartz
          npm i

      - name: Build
        run: |
          cd quartz
          npx quartz build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: quartz/public